version: '3.3'
services:
  grupo_a_postgres:
    image: postgres:13.2-alpine
    container_name: grupo_a_postgres
    env_file:
      - .env
    ports:
      - 6433:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
